# @package _global_

dataset:
  re10k:
    view_sampler:
      index_path: assets/evaluation_index_re10k.json

evaluation:
  methods:
    - name: Ours
      key: ours
      path: outputs/test/ours_public_rerun
    - name: Ours_old
      key: ours_old
      path: /local/home/botaye/Codes/pixelsplat/outputs/test/ablation_IntrinToken_lr5_nossim

  side_by_side_path: null
  animate_side_by_side: false
  highlighted:
    # Main Paper
    - scene: 32ce9b303717a29d
      target_index: 216
    - scene: 45e6fa48ddd00e87
      target_index: 127
    - scene: 7a13c5debea977a8
      target_index: 37

  output_metrics_path: baselines/re10k/evaluation_metrics.json