defaults:
  - base_dataset
  - view_sampler: bounded
  - optional view_sampler_dataset_specific_config@view_sampler: bounded_cambridge

name: cmabridge
roots: [/workspace/dataset/cambridge]
scenes: [GreatCourt, KingsCollege, OldHospital, ShopFacade, StMarysChurch]

input_image_shape: [256, 256]
original_image_shape: [1920, 1080]
cameras_are_circular: false

baseline_min: 1e-3
baseline_max: 1e2
max_fov: 100.0
